on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - name: Generate Binaries
      run: |
        CGO_ENABLED=0 GOOS=linux go build -mod=readonly -o dist/google-takeout-photo-location-fixer && \
        CGO_ENABLED=0 GOOS=darwin go build -mod=readonly -o dist/google-takeout-photo-location-fixer-darwin && \
        CGO_ENABLED=0 GOOS=darwin go build -mod=readonly -o dist/google-takeout-photo-location-fixer-darwin-arm64 && \
        CGO_ENABLED=0 GOOS=windows go build -mod=readonly -o dist/google-takeout-photo-location-fixer-windows.exe && \
    - name: build
      uses: ./.github/workflows/build.yaml
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
          README.md
          LICENSE
